export const POKEMONS = [
  {
    id: 1,
    name: 'Flareon',
    age: 5,
    type: 'Fire',
    abilities: ['Flame Charge', 'Fire Blast', 'Heat Wave', 'Quick Attack'],
    image_url: 'https://img.pokemondb.net/artwork/flareon.jpg',
  },
  {
    id: 2,
    name: 'Vaporeon',
    age: 4,
    type: 'Water',
    abilities: ['Water Gun', 'Hydro Pump', 'Aqua Ring', 'Muddy Water'],
    image_url: 'https://img.pokemondb.net/artwork/vaporeon.jpg',
  },
  {
    id: 3,
    name: 'Jolteon',
    age: 6,
    type: 'Electric',
    abilities: ['Thunder Shock', 'Volt Switch', 'Thunderbolt', 'Pin Missile'],
    image_url: 'https://img.pokemondb.net/artwork/jolteon.jpg',
  },
  {
    id: 4,
    name: 'Espeon',
    age: 3,
    type: 'Psychic',
    abilities: ['Confusion', 'Psybeam', 'Future Sight', 'Psychic'],
    image_url: 'https://img.pokemondb.net/artwork/espeon.jpg',
  },
  {
    id: 5,
    name: 'Umbreon',
    age: 5,
    type: 'Dark',
    abilities: ['Faint Attack', 'Dark Pulse', 'Shadow Ball', 'Moonlight'],
    image_url: 'https://img.pokemondb.net/artwork/umbreon.jpg',
  },
  {
    id: 6,
    name: 'Leafeon',
    age: 4,
    type: 'Grass',
    abilities: ['Razor Leaf', 'Leaf Blade', 'Solar Beam', 'Synthesis'],
    image_url: 'https://img.pokemondb.net/artwork/leafeon.jpg',
  },
  {
    id: 7,
    name: 'Glaceon',
    age: 3,
    type: 'Ice',
    abilities: ['Ice Shard', 'Ice Beam', 'Blizzard', 'Frost Breath'],
    image_url: 'https://img.pokemondb.net/artwork/glaceon.jpg',
  },
  {
    id: 8,
    name: 'Sylveon',
    age: 2,
    type: 'Fairy',
    abilities: ['Fairy Wind', 'Moonblast', 'Draining Kiss', 'Dazzling Gleam'],
    image_url: 'https://img.pokemondb.net/artwork/sylveon.jpg',
  },
  {
    id: 9,
    name: 'Pikachu',
    age: 5,
    type: 'Electric',
    abilities: ['Thunderbolt', 'Quick Attack', 'Iron Tail', 'Electro Ball'],
    image_url: 'https://img.pokemondb.net/artwork/pikachu.jpg',
  },
  {
    id: 10,
    name: 'Charizard',
    age: 7,
    type: 'Fire/Flying',
    abilities: ['Flamethrower', 'Dragon Claw', 'Fly', 'Blast Burn'],
    image_url: 'https://img.pokemondb.net/artwork/charizard.jpg',
  },
];

export const STATS = [
  {
    pokemon_id: 1,
    hp: 65,
    attack: 130,
    defense: 60,
    speed: 65,
    special_attack: 95,
  },
  {
    pokemon_id: 2,
    hp: 130,
    attack: 65,
    defense: 60,
    speed: 65,
    special_attack: 110,
  },
  {
    pokemon_id: 3,
    hp: 65,
    attack: 65,
    defense: 60,
    speed: 130,
    special_attack: 110,
  },
  {
    pokemon_id: 4,
    hp: 65,
    attack: 65,
    defense: 60,
    speed: 110,
    special_attack: 130,
  },
  {
    pokemon_id: 5,
    hp: 95,
    attack: 65,
    defense: 110,
    speed: 65,
    special_attack: 60,
  },
  {
    pokemon_id: 6,
    hp: 65,
    attack: 110,
    defense: 130,
    speed: 95,
    special_attack: 60,
  },
  {
    pokemon_id: 7,
    hp: 65,
    attack: 60,
    defense: 110,
    speed: 65,
    special_attack: 130,
  },
  {
    pokemon_id: 8,
    hp: 95,
    attack: 65,
    defense: 65,
    speed: 60,
    special_attack: 110,
  },
  {
    pokemon_id: 9,
    hp: 35,
    attack: 55,
    defense: 40,
    speed: 90,
    special_attack: 50,
  },
  {
    pokemon_id: 10,
    hp: 78,
    attack: 84,
    defense: 78,
    speed: 100,
    special_attack: 109,
  },
];
